CREATE SEQUENCE id_seq
START WITH 1
INCREMENT BY 1;

select * from USER_SEQUENCES;

create or replace ID_SEQUENCE_TRIGGER
BEFORE INSERT
ON board
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
	SELECT id_seq.nextval INTO :NEW.num FROM dual;
END;